import Foundation

enum Sources {
    static let cisaKEV = URL(string: "https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json")!
    static let nvd = URL(string: "https://services.nvd.nist.gov/rest/json/cves/2.0")!
    static let githubSearch = "https://api.github.com/search/repositories"

    static let rss: [FeedSource] = [
        .init(name: "CISA Advisories", url: URL(string: "https://www.cisa.gov/cybersecurity-advisories/all.xml")!, category: .alerts),
        .init(name: "NCSC UK", url: URL(string: "https://www.ncsc.gov.uk/api/1/services/v1/report-rss-feed.xml")!, category: .alerts),
        .init(name: "MSRC Update Guide", url: URL(string: "https://api.msrc.microsoft.com/update-guide/rss")!, category: .alerts),
        .init(name: "Zero Day Initiative", url: URL(string: "https://www.zerodayinitiative.com/rss/published/")!, category: .alerts),
        .init(name: "JPCERT", url: URL(string: "https://www.jpcert.or.jp/english/rss/jpcert-en.rdf")!, category: .alerts),
        .init(name: "Full Disclosure", url: URL(string: "https://seclists.org/rss/fulldisclosure.rss")!, category: .vulnerabilities),
        .init(name: "Exploit-DB", url: URL(string: "https://www.exploit-db.com/rss.xml")!, category: .vulnerabilities),
        .init(name: "Cisco Talos", url: URL(string: "https://blog.talosintelligence.com/rss/")!, category: .intelligence),
        .init(name: "Unit 42", url: URL(string: "https://unit42.paloaltonetworks.com/feed/")!, category: .intelligence),
        .init(name: "Microsoft Security", url: URL(string: "https://www.microsoft.com/en-us/security/blog/feed/")!, category: .intelligence),
        .init(name: "CrowdStrike", url: URL(string: "https://www.crowdstrike.com/blog/feed/")!, category: .intelligence),
        .init(name: "SentinelOne Labs", url: URL(string: "https://www.sentinelone.com/labs/feed/")!, category: .intelligence),
        .init(name: "WeLiveSecurity", url: URL(string: "https://www.welivesecurity.com/en/rss/feed/")!, category: .intelligence),
        .init(name: "Check Point Research", url: URL(string: "https://research.checkpoint.com/feed/")!, category: .intelligence),
        .init(name: "Trend Micro", url: URL(string: "https://feeds.trendmicro.com/TrendMicroResearch")!, category: .intelligence),
        .init(name: "Huntress", url: URL(string: "https://www.huntress.com/blog/rss.xml")!, category: .intelligence),
        .init(name: "Rapid7", url: URL(string: "https://blog.rapid7.com/rss/")!, category: .intelligence),
        .init(name: "Red Canary", url: URL(string: "https://redcanary.com/feed/")!, category: .intelligence),
        .init(name: "Malwarebytes Labs", url: URL(string: "https://www.malwarebytes.com/blog/feed/index.xml")!, category: .intelligence),
        .init(name: "Elastic Security Labs", url: URL(string: "https://www.elastic.co/security-labs/rss/feed.xml")!, category: .intelligence),
        .init(name: "Bitdefender Labs", url: URL(string: "https://www.bitdefender.com/blog/api/rss/labs/")!, category: .intelligence),
        .init(name: "Objective-See", url: URL(string: "https://objective-see.org/rss.xml")!, category: .intelligence),
        .init(name: "The Hacker News", url: URL(string: "https://feeds.feedburner.com/TheHackersNews")!, category: .news),
        .init(name: "BleepingComputer", url: URL(string: "https://www.bleepingcomputer.com/feed/")!, category: .news),
        .init(name: "The Record", url: URL(string: "https://therecord.media/feed")!, category: .news),
        .init(name: "SecurityWeek", url: URL(string: "https://www.securityweek.com/feed/")!, category: .news),
        .init(name: "Dark Reading", url: URL(string: "https://www.darkreading.com/rss.xml")!, category: .news),
        .init(name: "Infosecurity Mag", url: URL(string: "https://www.infosecurity-magazine.com/rss/news/")!, category: .news),
        .init(name: "CyberScoop", url: URL(string: "https://cyberscoop.com/feed/")!, category: .news),
        .init(name: "The Register", url: URL(string: "https://www.theregister.com/security/headlines.atom")!, category: .news),
        .init(name: "Help Net Security", url: URL(string: "https://www.helpnetsecurity.com/feed/")!, category: .news),
        .init(name: "Krebs on Security", url: URL(string: "https://krebsonsecurity.com/feed/")!, category: .news),
        .init(name: "Graham Cluley", url: URL(string: "https://grahamcluley.com/feed/")!, category: .news),
        .init(name: "Project Zero", url: URL(string: "https://googleprojectzero.blogspot.com/feeds/posts/default?alt=rss")!, category: .research),
        .init(name: "Google Security", url: URL(string: "https://security.googleblog.com/feeds/posts/default?alt=rss")!, category: .research),
        .init(name: "PortSwigger Research", url: URL(string: "https://portswigger.net/research/rss")!, category: .research),
        .init(name: "watchTowr Labs", url: URL(string: "https://labs.watchtowr.com/rss/")!, category: .research),
        .init(name: "Cloudflare", url: URL(string: "https://blog.cloudflare.com/rss/")!, category: .research),
        .init(name: "Schneier", url: URL(string: "https://www.schneier.com/feed/atom/")!, category: .research),
        .init(name: "Troy Hunt", url: URL(string: "https://www.troyhunt.com/rss/")!, category: .research),
        .init(name: "Trail of Bits", url: URL(string: "https://blog.trailofbits.com/feed/")!, category: .research),
        .init(name: "Qualys", url: URL(string: "https://blog.qualys.com/feed")!, category: .research),
        .init(name: "Tenable", url: URL(string: "https://www.tenable.com/blog/feed")!, category: .research),
        .init(name: "Wiz", url: URL(string: "https://www.wiz.io/blog/rss.xml")!, category: .research),
        .init(name: "Snyk", url: URL(string: "https://snyk.io/blog/feed/")!, category: .research),
        .init(name: "Horizon3", url: URL(string: "https://www.horizon3.ai/feed/")!, category: .research),
        .init(name: "Assetnote", url: URL(string: "https://blog.assetnote.io/feed.xml")!, category: .research),
        .init(name: "SANS ISC", url: URL(string: "https://isc.sans.edu/rssfeed_full.xml")!, category: .community),
        .init(name: "r/netsec", url: URL(string: "https://www.reddit.com/r/netsec/.rss")!, category: .community),
        .init(name: "r/blueteamsec", url: URL(string: "https://www.reddit.com/r/blueteamsec/.rss")!, category: .community),
    ]
}
